version: '3.9'

services:

  redis:
    image: redis:alpine
    command: redis-server

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - "4444:4444"   # Selenium

  weather_parser:
    build: ./
    container_name: weather_parser
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
#    volumes:
#      - .:/weather_parser
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
    links:
      - selenium


  celery_worker:
    build: ./
    container_name: celery_worker
    command: celery -A weather_parser worker -l info
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - weather_parser


  celery_beat:
    build: ./
    command: celery -A weather_parser beat -l info
    container_name: celery_beat
    depends_on:
      - redis
      - weather_parser
    restart: on-failure


  flower:
    build: ./
    container_name: flower
    command: celery -A weather_parser flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/2
      - FLOWER_PORT=5555
    depends_on:
      - redis
      - celery_worker